[package]
name = "raden_py"
version = "2026.0.0"
edition = "2024"
rust-version = "1.91"
description = "Python bindings for raden"
readme = "README.md"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]
name = "raden_py"

[dependencies]
pyo3 = { version = "0.29", features = ["abi3-py312", "extension-module", "experimental-inspect"] }
raden = "2026.2.0-canary.0"
