name: ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  rust:
    runs-on: ubuntu-26.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: rustup update stable
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings

  python:
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.14"
          - "3.14t"
          - "3.13"
          - "3.12"
    runs-on: ubuntu-26.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: rustup update stable
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: false
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: uv sync --extra dev
      - name: Run ruff check
        run: uv run ruff check .
      - name: Build wheel
        run: uv build --wheel --out-dir wheelhouse
      - name: Run tests
        run: uv run pytest
